//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題負責GoogleMap頁面.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Azure雲端上的期末資料庫Entities : DbContext
    {
        public Azure雲端上的期末資料庫Entities()
            : base("name=Azure雲端上的期末資料庫Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tStudio> tStudio { get; set; }
    
        public virtual ObjectResult<string> spGetCountyDistinctly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetCountyDistinctly");
        }
    }
}
