//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題負責GoogleMap頁面.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStudio
    {
        public int fId { get; set; }
        public string fCorpName { get; set; }
        public string fTaxId { get; set; }
        public string fPhone { get; set; }
        public string fEmail { get; set; }
        public string fPasswords { get; set; }
        public string fOwner { get; set; }
        public string fRepresentative { get; set; }
        public string fStudioNumber { get; set; }
        public string fCounty { get; set; }
        public string fDistrict { get; set; }
        public string fAddress { get; set; }
        public string cfImage { get; set; }
        public Nullable<float> fLongitude { get; set; }
        public Nullable<float> fLatitude { get; set; }
        public Nullable<System.DateTime> fRegisterTime { get; set; }
        public Nullable<bool> fActivated { get; set; }
        public string fNotification { get; set; }
    }
}
